schema_version: 1

context:
  name: google-cloud-documentai
  version: "3.10.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/google_cloud_documentai-${{ version }}.tar.gz
  sha256: fe6acc4d5a532d5d21ce3dd6cae3c103e6a4f3c63bb49b5ed7ff322d148cf483

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<3.15
    - google-api-core >=1.34.1,<3.0.0
    - google-auth >=2.14.1,<3.0.0
    - grpcio >=1.33.2,<2.0.0
    - proto-plus >=1.22.3,<2.0.0
    - protobuf >=3.20.2,<7.0.0

tests:
  - python:
      imports:
        - google.cloud.documentai_v1
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Google Cloud Documentai API client library
  description: |
    Document AI: Service to parse structured information from unstructured or semi-structured documents using state-of-the-art Google AI such as natural language, computer vision, translation, and AutoML.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-documentai

extra:
  recipe-maintainers:
    - MartinHoloubekQC
